version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app/cinema:/app
    
    command: sh -c "npm run dev"
    networks:
      - external
volumes:
  node_modules:
networks:
  external:
    external: true